        
spring:
  application:
    name: Catalogo_RD
    
  config:
    import: optional:configserver:http://localhost:8071 
    
  profiles:
    active: dev 


#attiva l'end point dell'actuator per il refresh delle proprietà di configurazione
#lette dal server di configurazione
management:
  endpoints:
    web:
      exposure:
        include: refresh